site_name: Helpwave Supportcenter
site_url: https://support.helpwave.de
theme:
  name: 'material'
nav:
  - Home: index.md
markdown_extensions:
  - codehilite
  - admonition
extra_css:
  - styles/extra.css
