site_name: Helpwave Supportcenter
site_url: https://support.helpwave.de
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/logo.svg'
  palette:
    primary: 'blue'
    accent: 'light-blue'
    scheme: 'default'
  font:
    text: 'Inter'
    code: 'Roboto Mono'
nav:
  - Impressum: https://cdn.helpwave.de/imprint.html
  - Datenschutz: https://cdn.helpwave.de/privacy.html
  - Home: index.md
markdown_extensions:
  - codehilite
  - admonition
extra_css:
  - styles/extra.css
#extra:
#  social:
#    - name: Impressum
#      link: https://cdn.helpwave.de/imprint.html
#    - name: Datenschutz
#      link: https://cdn.helpwave.de/privacy.html