site_name: Helpwave Supportcenter
site_url: https://support.helpwave.de
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/logo.svg'
  palette:
    primary: 'blue'
    accent: 'light-blue'
    scheme: 'default'
  font:
    text: 'Inter'
    code: 'Roboto Mono'
nav:
  - Home: index.md
markdown_extensions:
  - codehilite
  - admonition
extra_css:
  - styles/extra.css
